; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2.0.5 on Mon Oct 21 2019 00:00:01 GMT+0200 (Central European Summer Time)
G92 E0
G1 E-3 F3600  ; retract 10mm of filament
G92 E0
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0

