; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2.0.5 on Mon Oct 21 2019 00:00:01 GMT+0200 (Central European Summer Time)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
G92 E0
G1 E1 F3600         ; extrude 1mm of filament
G92 E0

