; G-Code generated by Simplify3D(R) Version 4.1.2
; Dec 25, 2020 at 6:36:00 PM
; Settings Summary
;   processName,Process1
;   applyToModels,150mmx150mm-level-test
;   profileName,HBot
;   profileVersion,2019-10-26 23:38:43
;   baseProfile,Default
;   printMaterial,PETG - SUNLU
;   printQuality,Medium
;   printExtruders,
;   extruderName,Extruder 1
;   extruderToolheadNumber,0
;   extruderDiameter,0.4
;   extruderAutoWidth,1
;   extruderWidth,0.48
;   extrusionMultiplier,1
;   extruderUseRetract,1
;   extruderRetractionDistance,4
;   extruderExtraRestartDistance,0
;   extruderRetractionZLift,0
;   extruderRetractionSpeed,5400
;   extruderUseCoasting,1
;   extruderCoastingDistance,0.2
;   extruderUseWipe,1
;   extruderWipeDistance,5
;   primaryExtruder,0
;   layerHeight,0.2
;   topSolidLayers,4
;   bottomSolidLayers,4
;   perimeterOutlines,4
;   printPerimetersInsideOut,1
;   startPointOption,3
;   startPointOriginX,110
;   startPointOriginY,300
;   sequentialIslands,0
;   spiralVaseMode,0
;   firstLayerHeightPercentage,100
;   firstLayerWidthPercentage,100
;   firstLayerUnderspeed,0.5
;   useRaft,0
;   raftExtruder,0
;   raftTopLayers,3
;   raftBaseLayers,2
;   raftOffset,3
;   raftSeparationDistance,0.18
;   raftTopInfill,100
;   aboveRaftSpeedMultiplier,0.3
;   useSkirt,0
;   skirtExtruder,0
;   skirtLayers,1
;   skirtOutlines,10
;   skirtOffset,0
;   usePrimePillar,0
;   primePillarExtruder,999
;   primePillarWidth,12
;   primePillarLocation,7
;   primePillarSpeedMultiplier,1
;   useOozeShield,0
;   oozeShieldExtruder,999
;   oozeShieldOffset,0.9
;   oozeShieldOutlines,2
;   oozeShieldSidewallShape,0
;   oozeShieldSidewallAngle,30
;   oozeShieldSpeedMultiplier,1.5
;   infillExtruder,0
;   internalInfillPattern,Fast Honeycomb
;   externalInfillPattern,Rectilinear
;   infillPercentage,20
;   outlineOverlapPercentage,25
;   infillExtrusionWidthPercentage,100
;   minInfillLength,5
;   infillLayerInterval,1
;   internalInfillAngles,0
;   overlapInternalInfillAngles,0
;   externalInfillAngles,45,-45
;   generateSupport,0
;   supportExtruder,0
;   supportInfillPercentage,25
;   supportExtraInflation,0
;   supportBaseLayers,0
;   denseSupportExtruder,0
;   denseSupportLayers,0
;   denseSupportInfillPercentage,70
;   supportLayerInterval,1
;   supportHorizontalPartOffset,0.3
;   supportUpperSeparationLayers,1
;   supportLowerSeparationLayers,1
;   supportType,0
;   supportGridSpacing,4
;   maxOverhangAngle,25
;   supportAngles,0
;   temperatureName,Extruder 1,Heated Bed
;   temperatureNumber,0,1
;   temperatureSetpointCount,2,1
;   temperatureSetpointLayers,1,2,1
;   temperatureSetpointTemperatures,225,215,85
;   temperatureStabilizeAtStartup,1,1
;   temperatureHeatedBed,0,1
;   fanLayers,1,5,10
;   fanSpeeds,0,5,20
;   blipFanToFullPower,1
;   adjustSpeedForCooling,1
;   minSpeedLayerTime,15
;   minCoolingSpeedSlowdown,20
;   increaseFanForCooling,0
;   minFanLayerTime,45
;   maxCoolingFanSpeed,35
;   increaseFanForBridging,1
;   bridgingFanSpeed,85
;   use5D,1
;   relativeEdistances,0
;   allowEaxisZeroing,1
;   independentExtruderAxes,0
;   includeM10123,0
;   stickySupport,1
;   applyToolheadOffsets,0
;   gcodeXoffset,0
;   gcodeYoffset,0
;   gcodeZoffset,0
;   overrideMachineDefinition,1
;   machineTypeOverride,0
;   strokeXoverride,210
;   strokeYoverride,210
;   strokeZoverride,150
;   originOffsetXoverride,0
;   originOffsetYoverride,0
;   originOffsetZoverride,0
;   homeXdirOverride,-1
;   homeYdirOverride,-1
;   homeZdirOverride,-1
;   flipXoverride,1
;   flipYoverride,-1
;   flipZoverride,1
;   toolheadOffsets,0,0|0,0|0,0|0,0|0,0|0,0
;   overrideFirmwareConfiguration,1
;   firmwareTypeOverride,RepRap (Marlin/Repetier/Sprinter)
;   GPXconfigOverride,r2
;   baudRateOverride,115200
;   overridePrinterModels,0
;   printerModelsOverride
;   startingGcode,G28 ; home all axes,G32 ; run bed.g -- probe bed and enable compensation
;   layerChangeGcode,
;   retractionGcode,
;   toolChangeGcode,
;   endingGcode,M0 ; call stop.g
;   exportFileFormat,gcode
;   celebration,0
;   celebrationSong,Random Song
;   postProcessing,
;   defaultSpeed,3600
;   outlineUnderspeed,0.5
;   solidInfillUnderspeed,0.8
;   supportUnderspeed,0.8
;   rapidXYspeed,18000
;   rapidZspeed,1200
;   minBridgingArea,50
;   bridgingExtraInflation,0
;   bridgingExtrusionMultiplier,0.96
;   bridgingSpeedMultiplier,1
;   useFixedBridgingAngle,0
;   fixedBridgingAngle,0
;   applyBridgingToPerimeters,0
;   filamentDiameters,1.75|1.75|1.75|1.75|1.75|1.75
;   filamentPricesPerKg,46|46|46|46|46|46
;   filamentDensities,1.25|1.25|1.25|1.25|1.25|1.25
;   useMinPrintHeight,0
;   minPrintHeight,20
;   useMaxPrintHeight,0
;   maxPrintHeight,15
;   useDiaphragm,0
;   diaphragmLayerInterval,20
;   robustSlicing,1
;   mergeAllIntoSolid,0
;   onlyRetractWhenCrossingOutline,1
;   retractBetweenLayers,0
;   useRetractionMinTravel,1
;   retractionMinTravel,3
;   retractWhileWiping,1
;   onlyWipeOutlines,1
;   avoidCrossingOutline,1
;   maxMovementDetourFactor,5
;   toolChangeRetractionDistance,12
;   toolChangeExtraRestartDistance,-0.5
;   toolChangeRetractionSpeed,600
;   externalThinWallType,1
;   internalThinWallType,1
;   thinWallAllowedOverlapPercentage,10
;   singleExtrusionMinLength,1
;   singleExtrusionMinPrintingWidthPercentage,50
;   singleExtrusionMaxPrintingWidthPercentage,150
;   singleExtrusionEndpointExtension,0.2
;   horizontalSizeCompensation,-0.1
G90
M82
M106 S0
M140 S85
M190 S85
M104 S225 T0
M109 S225 T0
G28 ; home all axes
G32 ; run bed.g -- probe bed and enable compensation
; process Process1
; layer 1, Z = 0.200
T0
G92 E0.0000
G1 E-4.0000 F5400
; feature outer perimeter
; tool H0.200 W0.480
G1 Z0.200 F1200
G1 X179.660 Y179.660 F18000
G1 E0.0000 F5400
G92 E0.0000
G1 X30.340 Y179.660 E5.9597 F900
G1 X30.340 Y30.340 E11.9194
G1 X179.660 Y30.340 E17.8791
G1 X179.660 Y179.460 E23.8308
G1 X179.660 Y179.660 F900
G1 X174.660 Y179.660 F900
G1 X178.340 Y178.340 F18000
G92 E0.0000
G1 X178.340 Y31.660 E5.8543 F900
G1 X31.660 Y31.660 E11.7086
G1 X31.660 Y178.340 E17.5629
G1 X178.140 Y178.340 E23.4093
G1 X178.340 Y178.340 F900
G1 X178.340 Y173.340 F900
; feature internal single extrusion
; tool H0.200 W0.720
G1 X179.000 Y178.460 F18000
G92 E0.0000
G1 X178.844 Y178.958 E0.0312 F900
G1 X178.748 Y178.983 E0.0372
G1 X178.652 Y178.997 E0.0430
G1 X178.556 Y179.000 E0.0487
G1 X31.444 Y179.000 E8.8561
G1 X31.348 Y178.997 E8.8619
G1 X31.252 Y178.983 E8.8677
G1 X31.156 Y178.958 E8.8736
G1 X31.042 Y178.844 E8.8833
G1 X31.017 Y178.748 E8.8892
G1 X31.003 Y178.652 E8.8950
G1 X31.000 Y178.556 E8.9007
G1 X31.000 Y31.444 E17.7081
G1 X31.003 Y31.348 E17.7139
G1 X31.017 Y31.252 E17.7197
G1 X31.042 Y31.156 E17.7256
G1 X31.156 Y31.042 E17.7353
G1 X31.252 Y31.017 E17.7412
G1 X31.348 Y31.003 E17.7470
G1 X31.444 Y31.000 E17.7528
G1 X178.556 Y31.000 E26.5601
G1 X178.652 Y31.003 E26.5659
G1 X178.748 Y31.017 E26.5717
G1 X178.844 Y31.042 E26.5776
G1 X178.958 Y31.156 E26.5873
G1 X178.983 Y31.252 E26.5932
G1 X178.997 Y31.348 E26.5990
G1 X179.000 Y31.444 E26.6048
G1 X179.000 Y178.260 E35.3944
G1 X179.000 Y178.460 F900
G92 E0.0000
G1 E-4.0000 F5400
; feature outer perimeter
; tool H0.200 W0.480
G1 X178.340 Y177.812 F18000
G1 X147.660 Y147.660
G1 E0.0000 F5400
G92 E0.0000
G1 X62.340 Y147.660 E3.4053 F900
G1 X62.340 Y62.340 E6.8106
G1 X147.660 Y62.340 E10.2159
G1 X147.660 Y147.460 E13.6132
G1 X147.660 Y147.660 F900
G1 X142.660 Y147.660 F900
G1 X146.340 Y146.340 F18000
G92 E0.0000
G1 X146.340 Y63.660 E3.2999 F900
G1 X63.660 Y63.660 E6.5999
G1 X63.660 Y146.340 E9.8998
G1 X146.140 Y146.340 E13.1918
G1 X146.340 Y146.340 F900
G1 X146.340 Y141.340 F900
; feature internal single extrusion
; tool H0.200 W0.720
G1 X147.000 Y146.460 F18000
G92 E0.0000
G1 X146.844 Y146.958 E0.0313 F900
G1 X146.748 Y146.983 E0.0372
G1 X146.652 Y146.997 E0.0430
G1 X146.556 Y147.000 E0.0487
G1 X63.444 Y147.000 E5.0245
G1 X63.348 Y146.997 E5.0303
G1 X63.252 Y146.983 E5.0361
G1 X63.156 Y146.958 E5.0420
G1 X63.042 Y146.844 E5.0517
G1 X63.017 Y146.748 E5.0576
G1 X63.003 Y146.652 E5.0634
G1 X63.000 Y146.556 E5.0692
G1 X63.000 Y63.444 E10.0450
G1 X63.003 Y63.348 E10.0507
G1 X63.017 Y63.252 E10.0565
G1 X63.042 Y63.156 E10.0625
G1 X63.156 Y63.042 E10.0721
G1 X63.252 Y63.017 E10.0781
G1 X63.348 Y63.003 E10.0839
G1 X63.444 Y63.000 E10.0896
G1 X146.556 Y63.000 E15.0654
G1 X146.652 Y63.003 E15.0712
G1 X146.748 Y63.017 E15.0770
G1 X146.844 Y63.042 E15.0829
G1 X146.958 Y63.156 E15.0926
G1 X146.983 Y63.252 E15.0985
G1 X146.997 Y63.348 E15.1043
G1 X147.000 Y63.444 E15.1101
G1 X147.000 Y146.260 E20.0682
G1 X147.000 Y146.460 F900
; layer 2, Z = 0.400
M104 S215 T0
; feature outer perimeter
; tool H0.200 W0.480
G1 Z0.400 F1200
G1 X147.660 Y147.660 F18000
G92 E0.0000
G1 X62.340 Y147.660 E3.4053 F1800
G1 X62.340 Y62.340 E6.8106
G1 X147.660 Y62.340 E10.2159
G1 X147.660 Y147.460 E13.6132
G1 X147.660 Y147.660 F1800
G1 X142.660 Y147.660 F1800
G1 X146.340 Y146.340 F18000
G92 E0.0000
G1 X146.340 Y63.660 E3.2999 F1800
G1 X63.660 Y63.660 E6.5999
G1 X63.660 Y146.340 E9.8998
G1 X146.140 Y146.340 E13.1918
G1 X146.340 Y146.340 F1800
G1 X146.340 Y141.340 F1800
; feature internal single extrusion
; tool H0.200 W0.720
G1 X147.000 Y146.460 F18000
G92 E0.0000
G1 X146.844 Y146.958 E0.0313 F1800
G1 X146.748 Y146.983 E0.0372
G1 X146.652 Y146.997 E0.0430
G1 X146.556 Y147.000 E0.0487
G1 X63.444 Y147.000 E5.0245
G1 X63.348 Y146.997 E5.0303
G1 X63.252 Y146.983 E5.0361
G1 X63.156 Y146.958 E5.0420
G1 X63.042 Y146.844 E5.0517
G1 X63.017 Y146.748 E5.0576
G1 X63.003 Y146.652 E5.0634
G1 X63.000 Y146.556 E5.0692
G1 X63.000 Y63.444 E10.0450
G1 X63.003 Y63.348 E10.0507
G1 X63.017 Y63.252 E10.0565
G1 X63.042 Y63.156 E10.0625
G1 X63.156 Y63.042 E10.0721
G1 X63.252 Y63.017 E10.0781
G1 X63.348 Y63.003 E10.0839
G1 X63.444 Y63.000 E10.0896
G1 X146.556 Y63.000 E15.0654
G1 X146.652 Y63.003 E15.0712
G1 X146.748 Y63.017 E15.0770
G1 X146.844 Y63.042 E15.0829
G1 X146.958 Y63.156 E15.0926
G1 X146.983 Y63.252 E15.0985
G1 X146.997 Y63.348 E15.1043
G1 X147.000 Y63.444 E15.1101
G1 X147.000 Y146.260 E20.0682
G1 X147.000 Y146.460 F1800
G92 E0.0000
G1 E-4.0000 F5400
; feature outer perimeter
; tool H0.200 W0.480
G1 X147.660 Y147.131 F18000
G1 X147.660 Y147.660
G1 X178.340 Y178.318
G1 X179.660 Y179.660
G1 E0.0000 F5400
G92 E0.0000
G1 X30.340 Y179.660 E5.9597 F1800
G1 X30.340 Y30.340 E11.9194
G1 X179.660 Y30.340 E17.8791
G1 X179.660 Y179.460 E23.8308
G1 X179.660 Y179.660 F1800
G1 X174.660 Y179.660 F1800
G1 X178.340 Y178.340 F18000
G92 E0.0000
G1 X178.340 Y31.660 E5.8543 F1800
G1 X31.660 Y31.660 E11.7086
G1 X31.660 Y178.340 E17.5629
G1 X178.140 Y178.340 E23.4093
G1 X178.340 Y178.340 F1800
G1 X178.340 Y173.340 F1800
; feature internal single extrusion
; tool H0.200 W0.720
G1 X179.000 Y178.460 F18000
G92 E0.0000
G1 X178.844 Y178.958 E0.0312 F1800
G1 X178.748 Y178.983 E0.0372
G1 X178.652 Y178.997 E0.0430
G1 X178.556 Y179.000 E0.0487
G1 X31.444 Y179.000 E8.8561
G1 X31.348 Y178.997 E8.8619
G1 X31.252 Y178.983 E8.8677
G1 X31.156 Y178.958 E8.8736
G1 X31.042 Y178.844 E8.8833
G1 X31.017 Y178.748 E8.8892
G1 X31.003 Y178.652 E8.8950
G1 X31.000 Y178.556 E8.9007
G1 X31.000 Y31.444 E17.7081
G1 X31.003 Y31.348 E17.7139
G1 X31.017 Y31.252 E17.7197
G1 X31.042 Y31.156 E17.7256
G1 X31.156 Y31.042 E17.7353
G1 X31.252 Y31.017 E17.7412
G1 X31.348 Y31.003 E17.7470
G1 X31.444 Y31.000 E17.7528
G1 X178.556 Y31.000 E26.5601
G1 X178.652 Y31.003 E26.5659
G1 X178.748 Y31.017 E26.5717
G1 X178.844 Y31.042 E26.5776
G1 X178.958 Y31.156 E26.5873
G1 X178.983 Y31.252 E26.5932
G1 X178.997 Y31.348 E26.5990
G1 X179.000 Y31.444 E26.6048
G1 X179.000 Y178.260 E35.3944
G1 X179.000 Y178.460 F1800
G92 E0.0000
G1 E-4.0000 F5400
; layer end
M0 ; call stop.g
; Build Summary
;   Build time: 0 hours 4 minutes
;   Filament length: 259.0 mm (0.26 m)
;   Plastic volume: 623.00 mm^3 (0.62 cc)
;   Plastic weight: 0.78 g (0.00 lb)
;   Material cost: 0.04
